/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as veriCredRegistrySol from './VeriCredRegistry.sol/index.js';
export type { veriCredRegistrySol };
export type { Counter } from './Counter.js';
export * as factories from './factories/index.js';
export { Counter__factory } from './factories/Counter__factory.js';
export type { AccredRegistry } from './VeriCredRegistry.sol/AccredRegistry.js';
export { AccredRegistry__factory } from './factories/VeriCredRegistry.sol/AccredRegistry__factory.js';