/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as veriCredRegistrySol from './VeriCredRegistry.sol/index.js';
export { Counter__factory } from './Counter__factory.js';